spring.application.name=chollywood
spring.datasource.url=jdbc:mysql://localhost:3306/chollywood

//ESTO LO CAMBIAS  SEGUN LA CONFIGURACION DE TU MYSQL
spring.datasource.username=root
spring.datasource.password=1234
//ESTO LO CAMBIAS  SEGUN LA CONFIGURACION DE TU MYSQL

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.thymeleaf.cache=false
